### ISSUE TITLE
Does not delete from a bucket

### ISSUE THREAD

**Issue by cyxou** [MathieuLoutre/grunt-aws-s3#74]
Got the folowing task:
`clean_dev: { options: { bucket: 'my.brand.new.bucket', debug: false},
   files: [{ dest: 'js', action: 'delete' }]}`

In command window it lists all the js files in the js folder and states that 4/4 objects deleted from my.brand.new.bucket. But in fact all the files persist.

**Comment by MathieuLoutre** [comment]
That's very strange. It worked fine last time I tested.
Do you get the progress bar in the console? Which version are you using?

**Comment by cyxou** [comment]
Hi, 
I use v0.13.1. And got no progress bar in the console:
![noname](https://cloud.githubusercontent.com/assets/5896622/8471458/1e266bf2-20a1-11e5-95be-eafc92131d0c.png)

The task on screenshot is as follows:
`clean_dev: {
        options: { bucket: s3DevBucket, debug: false},
        files: [
          {dest: '/', action: 'delete'},
        ]
      }`

**Comment by MathieuLoutre** [comment]
Hum, reading the code, the progress bar is only shown if you're _not_ in debug mode (https://github.com/MathieuLoutre/grunt-aws-s3/blob/master/tasks/aws_s3.js#L390). Now I see that you have `debug: false` in your config and by all means it should be working. But, out of curiosity, could you just remove the remove that from the config entirely? I'm suspecting the check for debug might be a little weak.

Alternatively, try logging some stuff around L448 (https://github.com/MathieuLoutre/grunt-aws-s3/blob/master/tasks/aws_s3.js#L448) to see if the deleteCall is being made at all.

**Comment by cyxou** [comment]
Hi! Sorry for the delay in getting back here. I've removed the debug property entirely but the problem persists. Had no time to investigate this issue getting deeper in your code....

**Comment by MathieuLoutre** [comment]
Hi @cyxou. I've tested this today with `0.14.1` and it's working as usual.

This is the config I'm using:

```js
			test_live: {
				options: {
					bucket: 'my-bucket',
					uploadConcurrency: 100,
					copyConcurrency: 100
				},
				files: [
					{ expand: true, dest: 'test/', cwd: 'dist/', src: ['*.js'], action: 'upload', params: { 'CacheControl': 'max-age=6000'} }
				]
			},
			clean_live: {
				options: {
					bucket: 'my-bucket',
					debug: false
				},
				files: [
					{ dest: 'test', action: "delete" }
				]
			},
```

Have you had any chance since? I'm closing since I can't reproduce but feel free to re-open.

**Comment by cyxou** [comment]
Hi @MathieuLoutre!

Sorry, I can't reproduce this too, because I've get rid of grunt and all it's stuff in favour of pure npm builds. Thanks for your efforts though.

**Comment by adrianmarinica** [comment]
Hi! I faced the same issue as @cyxou described. Basically, I could run the `delete` task as often as I wanted. Every time I ran it, it said that the files have been deleted. The files were still there though. The problem was that the key I was using did not have the `s3:DeleteObject` permission set to that key.

@MathieuLoutre The command line gives no error when you attempt to delete an object without having the proper permission.
